strategies_oblique = [
    "Abandon normal instruments",
    "Accept advice",
    "Accretion",
    "A line has two sides",
    "Allow an easement (an easement is the abandonment of a stricture)",
    "Are there sections? Consider transitions",
    "Ask people to work against their better judgment",
    "Ask your body",
    "Assemble some of the instruments in a group and treat the group",
    "Balance the consistency principle with the inconsistency principle",
    "Be dirty",
    "Breathe more deeply",
    "Bridges -build -burn",
    "Cascades",
    "Change instrument roles",
    "Change nothing and continue with immaculate consistency",
    "Children's voices -speaking -singing",
    "Cluster analysis",
    "Consider different fading systems",
    "Consult other sources -promising -unpromising",
    "Convert a melodic element into a rhythmic element",
    "Courage!",
    "Cut a vital connection",
    "Decorate, decorate",
    "Define an area as 'safe' and use it as an anchor",
    "Destroy -nothing -the most important thing",
    "Discard an axiom",
    "Disconnect from desire",
    "Discover the recipes you are using and abandon them",
    "Distorting time",
    "Do nothing for as long as possible",
    "Don't be afraid of things because they're easy to do",
    "Don't be frightened of cliches",
    "Don't be frightened to display your talents",
    "Don't break the silence",
    "Don't stress one thing more than another",
    "Do something boring",
    "Do the washing up",
    "Do the words need changing?",
    "Do we need holes?",
    "Emphasize differences",
    "Emphasize repetitions",
    "Emphasize the flaws",
    "Faced with a choice, do both (given by Dieter Roth)",
    "Feedback recordings into an acoustic situation",
    "Fill every beat with something",
    "Get your neck massaged",
    "Ghost echoes",
    "Give the game away",
    "Give way to your worst impulse",
    "Go slowly all the way round the outside",
    "Honor thy error as a hidden intention",
    "How would you have done it?",
    "Humanize something free of error",
    "Imagine the music as a moving chain or caterpillar",
    "Imagine the music as a set of disconnected events",
    "Infinitesimal gradations",
    "Intentions -credibility of -nobility of -humility of",
    "Into the impossible",
    "Is it finished?",
    "Is there something missing?",
    "Is the tuning appropriate?",
    "Just carry on",
    "Left channel, right channel, center channel",
    "Listen in total darkness, or in a very large room, very quietly",
    "Listen to the quiet voice",
    "Look at a very small object; look at its center",
    "Look at the order in which you do things",
    "Look closely at the most embarrassing details and amplify them",
    "Lowest common denominator check -single beat -single note -single riff",
    "Make a blank valuable by putting it in an exquisite frame",
    "Make an exhaustive list of everything you might do and do the last thing on the list",
    "Make a sudden, destructive, unpredictable action; incorporate",
    "Mechanicalize something idiosyncratic",
    "Mute and continue",
    "Only one element of each kind",
    "(Organic) machinery",
    "Overtly resist change",
    "Put in earplugs",
    "Remember those quiet evenings",
    "Remove ambiguities and convert to specifics",
    "Remove specifics and convert to ambiguities",
    "Repetition is a form of change",
    "Reverse",
    "Short circuit",
    "Shut the door and listen from outside",
    "Simple subtraction",
    "Spectrum analysis",
    "Take a break",
    "Take away the elements in order of apparent non-importance",
    "Tape your mouth (given by Ritva Saarikko)",
    "The inconsistency principle",
    "The tape is now the music",
    "Think of the radio",
    "Tidy up",
    "Trust in the you of now",
    "Turn it upside down",
    "Twist the spine",
    "Use an old idea",
    "Use an unacceptable color",
    "Use fewer notes",
    "Use filters",
    "Use 'unqualified' people",
    "Water",
    "What are you really thinking about just now? Incorporate",
    "What is the reality of the situation?",
    "What mistakes did you make last time?",
    "What would your closest friend do?",
    "What wouldn't you do?",
    "Work at a different speed",
    "You are an engineer",
    "You can only make one dot at a time",
    "You don't have to be ashamed of using your own ideas",
    "[blank white card]",
]

strategies_alchemist = [
    "Forsake customary tools",
    "Heed wise counsel",
    "Gradual accumulation",
    "A path has two sides",
    "Grant a passage (a passage is the relinquishing of a restriction)",
    "Are there chapters? Consider transitions",
    "Invite others to defy their better judgment",
    "Consult your physical vessel",
    "Gather select instruments and treat them as one",
    "Harmonize the principle of constancy with the principle of change",
    "Embrace the unclean",
    "Draw deeper breaths",
    "Bridges -forge -consume",
    "Waterfalls",
    "Alter the roles of the instruments",
    "Change nothing and continue with flawless consistency",
    "Children's voices -speaking -singing",
    "Group analysis",
    "Contemplate various fading methods",
    "Seek other sources -hopeful -bleak",
    "Transform a melodic element into a rhythmic one",
    "Summon courage!",
    "Sever a crucial connection",
    "Adorn, adorn",
    "Designate a 'safe' area and use it as an anchor",
    "Destroy -nothing -the most crucial element",
    "Dispel a fundamental truth",
    "Detach from desire",
    "Uncover the formulas you employ and discard them",
    "Distort time",
    "Do nothing for as long as possible",
    "Fear not the simple tasks",
    "Do not dread the common phrases",
    "Do not fear to show your talents",
    "Maintain silence",
    "Do not emphasize one thing over another",
    "Engage in something mundane",
    "Cleanse the utensils",
    "Should the words be altered?",
    "Do we require voids?",
    "Highlight differences",
    "Accentuate repetitions",
    "Magnify imperfections",
    "When faced with a choice, do both (advice from Dieter Roth)",
    "Feed recordings into an acoustic realm",
    "Fill each beat with purpose",
    "Receive a neck massage",
    "Echoes of spirits",
    "Reveal the secret",
    "Yield to your darkest impulse",
    "Slowly traverse the outer periphery",
    "Honor errors as hidden intentions",
    "How might you have done it?",
    "Humanize the flawless",
    "Envision the music as a moving chain or caterpillar",
    "See the music as separate events",
    "Infinitesimal adjustments",
    "Intentions -credibility -nobility -humility",
    "Into the unknown",
    "Is it complete?",
    "Is something missing?",
    "Is the tuning right?",
    "Just continue",
    "Left channel, right channel, center channel",
    "Listen in darkness, or in a vast space, very softly",
    "Hear the quiet voice",
    "Gaze at a tiny object; focus on its center",
    "Observe the sequence of your actions",
    "Scrutinize the most embarrassing details and amplify them",
    "Lowest common denominator check -single beat -single note -single riff",
    "Make a blank valuable by placing it in an exquisite frame",
    "List everything you might do and do the last thing on the list",
    "Make a sudden, destructive, unpredictable move; incorporate",
    "Mechanize something unique",
    "Mute and proceed",
    "Only one of each kind",
    "Living machinery",
    "Resist change openly",
    "Wear earplugs",
    "Recall the quiet evenings",
    "Remove ambiguities and specify",
    "Remove specifics and create ambiguities",
    "Repetition is change",
    "Invert",
    "Create a shortcut",
    "Close the door and listen from outside",
    "Simple subtraction",
    "Analyze the spectrum",
    "Take a respite",
    "Remove elements in order of apparent insignificance",
    "Tape your mouth (advice from Ritva Saarikko)",
    "The principle of inconsistency",
    "The tape is now the music",
    "Think of the radio",
    "Tidy up",
    "Trust in your present self",
    "Invert it",
    "Twist the spine",
    "Revive an old idea",
    "Use a forbidden color",
    "Employ fewer notes",
    "Use filters",
    "Engage 'unqualified' individuals",
    "Water",
    "What occupies your mind now? Incorporate it",
    "What is the true nature of the situation?",
    "What errors were made before?",
    "What would your closest confidant do?",
    "What would you avoid?",
    "Work at a different pace",
    "You are a creator",
    "One dot at a time",
    "Do not be ashamed of your own ideas",
    "[blank white card]",
]

strategies_prophet = [
    "Abandon thine ordinary tools",
    "Embrace the wisdom of others",
    "Accumulate slowly and steadily",
    "Every path hath two sides",
    "Permit a way through (a way through is the relinquishing of a barrier)",
    "Discern the chapters; consider their transitions",
    "Invite others to challenge their better judgment",
    "Seek counsel from thy physical form",
    "Gather thy instruments and treat them as one",
    "Balance the law of constancy with the law of change",
    "Embrace the unclean",
    "Breathe deeply and fully",
    "Build bridges; burn bridges",
    "Witness the cascading waters",
    "Change the roles of thy instruments",
    "Change naught and continue with unwavering consistency",
    "Hearken to the voices of children -speaking -singing",
    "Analyze in clusters",
    "Contemplate varied fading methods",
    "Consult various sources -hopeful -hopeless",
    "Transform a melody into a rhythm",
    "Summon thy courage!",
    "Sever a vital connection",
    "Adorn with beauty, adorn",
    "Mark a place as 'safe' and anchor thyself there",
    "Destroy naught, or destroy the most important",
    "Cast away an axiom",
    "Detach from desire",
    "Uncover and forsake thy recipes",
    "Distort time",
    "Do nothing for as long as possible",
    "Fear not the simple tasks",
    "Be not afraid of common sayings",
    "Show thy talents without fear",
    "Maintain the silence",
    "Stress not one thing over another",
    "Engage in the mundane",
    "Cleanse thy surroundings",
    "Should the words be altered?",
    "Do we need voids?",
    "Highlight the differences",
    "Accentuate the repetitions",
    "Magnify the imperfections",
    "When faced with a choice, do both (thus spoke Dieter Roth)",
    "Feed recordings into an acoustic realm",
    "Fill each beat with purpose",
    "Receive a neck massage",
    "Echoes of spirits",
    "Reveal the game",
    "Yield to thy darkest impulse",
    "Slowly traverse the periphery",
    "Honor errors as hidden intentions",
    "How wouldst thou have done it?",
    "Humanize the flawless",
    "Envision the music as a moving chain or caterpillar",
    "See the music as separate events",
    "Infinitesimal adjustments",
    "Intentions -credibility -nobility -humility",
    "Into the unknown",
    "Is it complete?",
    "Is something missing?",
    "Is the tuning right?",
    "Just continue",
    "Left channel, right channel, center channel",
    "Listen in darkness, or in a vast space, very softly",
    "Hearken to the quiet voice",
    "Gaze upon a tiny object; focus on its center",
    "Observe the sequence of thy actions",
    "Scrutinize the most embarrassing details and amplify them",
    "Lowest common denominator check -single beat -single note -single riff",
    "Make a blank valuable by placing it in an exquisite frame",
    "List all thy possible actions and perform the last one",
    "Make a sudden, destructive, unpredictable move; incorporate",
    "Mechanize something unique",
    "Mute and proceed",
    "Only one of each kind",
    "Living machinery",
    "Resist change openly",
    "Wear earplugs",
    "Recall the quiet evenings",
    "Remove ambiguities and specify",
    "Remove specifics and create ambiguities",
    "Repetition is change",
    "Invert",
    "Create a shortcut",
    "Close the door and listen from outside",
    "Simple subtraction",
    "Analyze the spectrum",
    "Take a respite",
    "Remove elements in order of apparent insignificance",
    "Tape thy mouth (thus spoke Ritva Saarikko)",
    "The principle of inconsistency",
    "The tape is now the music",
    "Think of the radio",
    "Tidy up",
    "Trust in thy present self",
    "Invert it",
    "Twist the spine",
    "Revive an old idea",
    "Use a forbidden color",
    "Employ fewer notes",
    "Use filters",
    "Engage 'unqualified' individuals",
    "Water",
    "What occupies thy mind now? Incorporate it",
    "What is the true nature of the situation?",
    "What errors were made before?",
    "What would thy closest confidant do?",
    "What wouldst thou avoid?",
    "Work at a different pace",
    "Thou art a creator",
    "One dot at a time",
    "Be not ashamed of thine own ideas",
    "[blank white card]",
]
